[package]
name = "wastebin"
version = "2.7.0"
edition = "2021"
rust-version = "1.83"

[dependencies]
askama = { version = "0.12", default-features = false, features = ["with-axum"] }
askama_axum = { version = "0.4" }
async-compression = { version = "0.4", features = ["tokio", "zstd"] }
axum = { version = "0.7", features = ["json", "query"] }
axum-extra = { version = "0.9", features = ["cookie-signed", "typed-header"] }
bytes = "1"
chacha20poly1305 = "0.10.1"
hex = "0.4"
lru = "0.12"
mime = "0.3"
qrcodegen = "1"
rand = "0.8"
rusqlite = { version = "0.32", features = ["bundled"] }
rusqlite_migration = { version = "1", default-features = false }
rust-argon2 = "2.0.0"
sha2 = "0.10"
serde = { version = "1", features = ["derive"] }
syntect = { version = "5", default-features = false, features = ["html", "plist-load", "regex-fancy"] }
thiserror = "2"
time = { version = "0.3", features = ["macros", "serde"] }
tokio = { version = "1", features = ["full"] }
tower = { version = "0.5", default-features = false }
tower-http = { version = "0.6", features = ["compression-full", "limit", "timeout", "trace"] }
tracing = "0.1"
tracing-subscriber = "0.3"
url = "2"
zstd = "0.13"
parking_lot = "0.12.1"
http = "1.1.0"

[dev-dependencies]
reqwest = { version = "0.12", default-features = false, features = ["cookies", "json"] }
tower = { version = "0.5", default-features = false, features = ["util", "make"] }
tower-service = "0.3"

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
cast_possible_truncation = "deny"
cast_possible_wrap = "deny"
cast_sign_loss = "deny"
enum_glob_use = "deny"
if_not_else = "deny"
items_after_statements = "deny"
mut_mut = "deny"
panic = "deny"
pedantic = "deny"
print_stdout = "deny"
similar_names = "deny"
unicode_not_nfc = "deny"
unwrap_used = "deny"
used_underscore_binding = "deny"

[profile.release]
strip = "debuginfo"
lto = "fat"
