name: Rust

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test and lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Install Rust
      uses: dtolnay/rust-toolchain@1.85.0
      with:
        components: clippy,rustfmt
    - run: cargo clippy
    - run: cargo fmt --all --check
    - run: cargo test --all-targets

  spaces-check:
    name: Spaces Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Spaces check
        run: git diff-tree --check $(git hash-object -t tree /dev/null) HEAD
